version: '2'

services:
  miinto.productcentre.locationstatus.worker:
    image: miinto.productcentre.locationstatus.worker
    build:
      context: ./Miinto.ProductCentre.LocationStatus.Worker
      dockerfile: Dockerfile
